# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f18abe62db91e12c7d1a8c9b1f635b66a772f6112b4f3325f9780f791455da30d0dc364ef101aa2465fdc264207dfc9644f3200938a451105bfb881426a4dc2b

test:
  secret_key_base: 0e2692f599acffec5f3e010e64c5235d1a7fa7709e4aa5a8d61bf161714339b51dd21c7336caa9f19845f584fada5802b9d411223e9a1cc502b238c8880e1adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
